FROM --platform=$BUILDPLATFORM docker.io/golang:1.25.3-alpine3.22 AS builder
ARG TARGETARCH
ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=${TARGETARCH}

WORKDIR /src
COPY ./go.* ./
RUN go mod download
COPY ./ ./
RUN go build -ldflags="-s -w" -o /app
USER 1000
EXPOSE 8080
ENTRYPOINT ["/app"]