FROM --platform=$BUILDPLATFORM docker.io/golang:1.25.2-alpine3.22 AS builder
ARG TARGETARCH
ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=${TARGETARCH}

COPY ./go.* ./
RUN go mod download
COPY ./ ./
RUN go build -ldflags="-s -w" -o /app

FROM gcr.io/distroless/static
COPY --from=builder /app /app
USER 1000
ENTRYPOINT ["/app"]