apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
  namespace: default
spec:
  containers:
    - image: test
      name: test-pod
      imagePullPolicy: IfNotPresent
      resources: {}
      securityContext:
        runAsNonRoot: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
